### PR TITLE
Define modules inline in the Module section instead of in the ModuleCode section

### PR DESCRIPTION
**Pull request by lukewagner**
As discussed in #9.

### CODE REVIEW

**Comment by lukewagner** [comment]
(Also #22)

**Comment by lukewagner** [comment]
(Also #8)

**Review by alexcrichton — APPROVED** [review]
I believe this should fully resolve and close #9 and #22, although #8 will need the other modifications to `alias` discussed where the sugar in the text format isn't based on identifiers but rather strings like `(func $instance_name "export_name")`.

Looks great though!

**Comment by lukewagner** [comment]
Ah, right, thanks.

**Pull request merged**
